# Generated by Django 4.2.4 on 2024-03-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoeinventory',
            options={'ordering': ('product',), 'verbose_name_plural': 'shoe inventories'},
        ),
    ]
